name: advent_of_code
description: Advent of Code
# version: 1.0.0
# homepage: https://github.com/praful/advent_of_code

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  collection: ^1.15.0
  trotter: ^2.0.0-dev.1
  tuple: ^2.0.0-nullsafety.0
  dartz: ^0.10.0-nullsafety.1
  # basics: any
  pedantic: ^1.11.0
# dev_dependencies:
# pedantic: ^1.11.0
