name: advent_of_code
description: Advent of Code
# version: 1.0.0
# homepage: https://github.com/praful/advent_of_code

environment:
  sdk: ">=2.8.1 <3.0.0"

dependencies:
  collection: any
  trotter: any
  tuple: any
  basics: any

dev_dependencies:
  pedantic: ^1.9.0
